apiVersion: v2
name: harp-proxy
description: HTTP API Runtime Proxy
type: application
version: "0.7.4"
appVersion: "0.7.6"

dependencies:
  - name: postgresql
    version: 16.0.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
